
import { getProjectImage } from '../../lib/image-service';
import { ProjectTemplate } from '../../lib/ProjectTypes';

export const projectTemplates: ProjectTemplate[] = [
  // Software Projects (original 10 + 5 new)
  {
    id: 'software-1',
    type: 'software',
    title: 'To-Do List App',
    description: 'A simple app to manage tasks with add, edit, and delete functionality.',
    image: getProjectImage('To-Do List App'),
    category: 'Web',
    difficulty: 'Beginner',
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Task creation', 'Task completion', 'Local storage'],
      code: '// Sample React component\nfunction TodoList() {\n  const [todos, setTodos] = useState([]);\n  // Add todo logic\n}',
      tutorials: [
        { id: 1, step: 'Set up React project', completed: false },
        { id: 2, step: 'Create Todo component', completed: false },
        { id: 3, step: 'Add local storage', completed: false },
      ],
    },
  },
  {
    id: 'software-2',
    type: 'software',
    title: 'Weather App',
    description: 'A weather forecasting app using a public API.',
    image: getProjectImage('Weather App'),
    category: 'Web',
    difficulty: 'Intermediate',
    skills: ['HTML', 'CSS', 'JavaScript', 'API'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Current weather', '5-day forecast', 'Location search'],
      code: '// Sample API fetch\nasync function getWeather(city) {\n  const response = await fetch(`https://api.openweathermap.org/data/2.5/weather?q=${city}`);\n  return response.json();\n}',
      tutorials: [
        { id: 1, step: 'Create UI layout', completed: false },
        { id: 2, step: 'Integrate weather API', completed: false },
        { id: 3, step: 'Display forecast', completed: false },
      ],
    },
  },
  {
    id: 'software-3',
    type: 'software',
    title: 'Number Guessing Game',
    description: 'A game where users guess a random number between 1 and 100.',
    image: getProjectImage('Number Guessing Game'),
    category: 'Web',
    difficulty: 'Beginner',
    skills: ['HTML', 'CSS', 'JavaScript'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Random number generation', 'User input', 'Feedback messages'],
      code: '// Sample JavaScript game\nlet number = Math.floor(Math.random() * 100) + 1;\nfunction guessNumber(userGuess) {\n  if (userGuess == number) return "Correct!";\n  return userGuess < number ? "Too low!" : "Too high!";\n}',
      tutorials: [
        { id: 1, step: 'Create game interface', completed: false },
        { id: 2, step: 'Add guessing logic', completed: false },
        { id: 3, step: 'Display feedback', completed: false },
      ],
    },
  },
  {
    id: 'software-4',
    type: 'software',
    title: 'Chat Application',
    description: 'A real-time chat app with multiple users.',
    image: getProjectImage('Chat Application'),
    category: 'Web',
    difficulty: 'Advanced',
    skills: ['React', 'Node.js', 'WebSocket', 'CSS'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Real-time messaging', 'User authentication', 'Chat rooms'],
      code: '// Sample WebSocket setup\nconst socket = new WebSocket("ws://your-server.com");\nsocket.onmessage = (event) => {\n  console.log("Message:", event.data);\n};',
      tutorials: [
        { id: 1, step: 'Set up backend server', completed: false },
        { id: 2, step: 'Implement WebSocket', completed: false },
        { id: 3, step: 'Create chat UI', completed: false },
      ],
    },
  },
  {
    id: 'software-5',
    type: 'software',
    title: 'Photo Gallery',
    description: 'A responsive photo gallery with upload functionality.',
    image: getProjectImage('Photo Gallery'),
    category: 'Web',
    difficulty: 'Intermediate',
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Image upload', 'Grid layout', 'Lightbox view'],
      code: '// Sample React component\nfunction Gallery() {\n  const [images, setImages] = useState([]);\n  // Image upload logic\n}',
      tutorials: [
        { id: 1, step: 'Create gallery layout', completed: false },
        { id: 2, step: 'Add upload functionality', completed: false },
        { id: 3, step: 'Implement lightbox', completed: false },
      ],
    },
  },
  {
    id: 'software-6',
    type: 'software',
    title: 'E-commerce Store',
    description: 'A basic online store with product listings and cart.',
    image: getProjectImage('E-commerce Store'),
    category: 'Web',
    difficulty: 'Advanced',
    skills: ['React', 'Node.js', 'MongoDB', 'CSS'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Product catalog', 'Shopping cart', 'Checkout'],
      code: '// Sample product fetch\nasync function getProducts() {\n  const response = await fetch("/api/products");\n  return response.json();\n}',
      tutorials: [
        { id: 1, step: 'Set up database', completed: false },
        { id: 2, step: 'Create product listing', completed: false },
        { id: 3, step: 'Implement cart', completed: false },
      ],
    },
  },
  {
    id: 'software-7',
    type: 'software',
    title: 'Blog Platform',
    description: 'A blogging platform with post creation and comments.',
    image: getProjectImage('Blog Platform'),
    category: 'Web',
    difficulty: 'Intermediate',
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Post creation', 'Comment system', 'User profiles'],
      code: `// Sample post component\nfunction Post({ title, content }) {\n  return <div>{title}</div>;\n}`,
      tutorials: [
        { id: 1, step: 'Create blog layout', completed: false },
        { id: 2, step: 'Add post functionality', completed: false },
        { id: 3, step: 'Implement comments', completed: false },
      ],
    },
  },
  {
    id: 'software-8',
    type: 'software',
    title: 'Task Scheduler',
    description: 'A calendar-based task scheduling application.',
    image: getProjectImage('Task Scheduler'),
    category: 'Web',
    difficulty: 'Intermediate',
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Calendar view', 'Task assignment', 'Reminders'],
      code: '// Sample calendar component\nfunction Calendar() {\n  const [date, setDate] = useState(new Date());\n  // Calendar logic\n}',
      tutorials: [
        { id: 1, step: 'Create calendar UI', completed: false },
        { id: 2, step: 'Add task functionality', completed: false },
        { id: 3, step: 'Implement reminders', completed: false },
      ],
    },
  },
  {
    id: 'software-9',
    type: 'software',
    title: 'Music Player',
    description: 'A web-based music player with playlist support.',
    image: getProjectImage('Music Player'),
    category: 'Web',
    difficulty: 'Intermediate',
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Play/pause controls', 'Playlist management', 'Progress bar'],
      code: '// Sample audio component\nfunction AudioPlayer() {\n  const audioRef = useRef(null);\n  // Audio controls\n}',
      tutorials: [
        { id: 1, step: 'Create player UI', completed: false },
        { id: 2, step: 'Add audio controls', completed: false },
        { id: 3, step: 'Implement playlist', completed: false },
      ],
    },
  },
  {
    id: 'software-10',
    type: 'software',
    title: 'Note Taking App',
    description: 'A digital note-taking app with rich text editing.',
    image: getProjectImage('Note Taking App'),
    category: 'Web',
    difficulty: 'Intermediate',
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Rich text editor', 'Note categories', 'Search functionality'],
      code: '// Sample note component\nfunction NoteEditor() {\n  const [content, setContent] = useState("");\n  // Editor logic\n}',
      tutorials: [
        { id: 1, step: 'Create editor UI', completed: false },
        { id: 2, step: 'Add rich text features', completed: false },
        { id: 3, step: 'Implement search', completed: false },
      ],
    },
  },
  // New Software Projects
  {
    id: 'software-11',
    type: 'software',
    title: 'Portfolio Website',
    description: 'A personal portfolio site to showcase projects and skills.',
    image: getProjectImage('Portfolio Website'),
    category: 'Web',
    difficulty: 'Beginner',
    skills: ['HTML', 'CSS', 'JavaScript'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Responsive design', 'Project showcase', 'Contact form'],
      code: '// Sample JS for contact form\n function submitForm() { console.log("Form submitted"); }',
      tutorials: [
        { id: 1, step: 'Set up HTML structure', completed: false },
        { id: 2, step: 'Add CSS styling', completed: false },
        { id: 3, step: 'Implement interactivity', completed: false },
      ],
    },
  },
  {
    id: 'software-12',
    type: 'software',
    title: 'Calculator App',
    description: 'A basic calculator for arithmetic operations.',
    image: getProjectImage('Calculator App'),
    category: 'Web',
    difficulty: 'Beginner',
    skills: ['HTML', 'CSS', 'JavaScript'],
    progress: 0,
    content : {
      type: 'web',
      features: ['Basic operations', 'Display screen', 'Button inputs'],
        code: '// Sample calculator logic\nfunction calculate(op, a, b) {\n  switch(op) { case "+": return a + b; /* etc */ }'},
        tutorials: [
          { id: 1, step: 'Create UI buttons', completed: false },
          { id: 2, step: 'Add calculation logic', completed: false },
          { id: 3, step: 'Handle errors', completed: false },
        ],
      },
      
  {
    id: 'software-13',
    type: 'software',
    title: 'Quiz Game',
    description: 'An interactive quiz application with scoring.',
    image: getProjectImage('Quiz Game'),
    category: 'Web',
    difficulty: 'Intermediate',
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Multiple questions', 'Scoring system', 'Timer'],
      code: '// Sample quiz state\n const [score, setScore] = useState(0);',
      tutorials: [
        { id: 1, step: 'Set up questions', completed: false },
        { id: 2, step: 'Add scoring', completed: false },
        { id: 3, step: 'Implement timer', completed: false },
      ],
    },
  },
  {
    id: 'software-14',
    type: 'software',
    title: 'Social Media Clone',
    description: 'A simplified version of a social media platform.',
    image: getProjectImage('Social Media Clone'),
    category: 'Web',
    difficulty: 'Advanced',
    skills: ['React', 'Node.js', 'MongoDB'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Posting', 'Liking', 'Commenting'],
      code: '// Sample post API\n async function createPost(post) { /* fetch */ }',
      tutorials: [
        { id: 1, step: 'Set up backend', completed: false },
        { id: 2, step: 'Create frontend', completed: false },
        { id: 3, step: 'Integrate features', completed: false },
      ],
    },
  },
  {
    id: 'software-15',
    type: 'software',
    title: 'Blog CMS',
    description: 'A content management system for blogs.',
    image: getProjectImage('Blog CMS'),
    category: 'Web',
    difficulty: 'Advanced',
    skills: ['React', 'Node.js', 'SQL'],
    progress: 0,
    content: {
      type: 'web',
      features: ['Post editing', 'User management', 'SEO tools'],
      code: '// Sample CMS logic\n function editPost(id, content) { /* update */ }',
      tutorials: [
        { id: 1, step: 'Database setup', completed: false },
        { id: 2, step: 'Admin panel', completed: false },
        { id: 3, step: 'Frontend integration', completed: false },
      ],
    },
  },
  // Science Projects (original 10 + 5 new, fixed image URLs)
  {
    id: 'science-1',
    type: 'science',
    title: 'Solar System Model',
    description: 'Create a static model of the solar system to understand planetary orbits and relative sizes.',
    image: getProjectImage('Solar System Model'),
    category: 'Science',
    difficulty: 'Beginner',
    skills: ['Astronomy', 'Crafting', 'Measurement'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Planetary arrangement', 'Orbit paths', 'Relative scale'],
      tutorials: [
        { id: 1, step: 'Gather materials and paint styrofoam balls', completed: false },
        { id: 2, step: 'Arrange planets on a base with orbit paths', completed: false },
        { id: 3, step: 'Label planets and add details', completed: false },
      ],
      components: ['Styrofoam balls (various sizes)', 'Wooden dowels', 'Cardboard base', 'Acrylic paint', 'Glue', 'Markers'],
    },
  },
  {
    id: 'science-2',
    type: 'science',
    title: 'Volcano Model',
    description: 'Build a static model of a volcano to learn about its structure and geological features.',
    image: getProjectImage('Volcano Model'),
    category: 'Science',
    difficulty: 'Beginner',
    skills: ['Geology', 'Crafting', 'Modeling'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Crater structure', 'Layered rock formation', 'Labeling parts'],
      tutorials: [
        { id: 1, step: 'Create a base and mold the volcano shape', completed: false },
        { id: 2, step: 'Paint and add texture to the model', completed: false },
        { id: 3, step: 'Label volcano parts (crater, magma chamber)', completed: false },
      ],
      components: ['Clay or papier-mâché', 'Cardboard base', 'Acrylic paint', 'Small container (for crater)', 'Glue', 'Labels'],
    },
  },
  {
    id: 'science-3',
    type: 'science',
    title: 'Water Cycle Model',
    description: 'Construct a static model to illustrate the stages of the water cycle.',
    image: getProjectImage('Water Cycle Model'),
    category: 'Science',
    difficulty: 'Beginner',
    skills: ['Environmental Science', 'Crafting', 'Diagramming'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Evaporation', 'Condensation', 'Precipitation'],
      tutorials: [
        { id: 1, step: 'Create a base and add water body', completed: false },
        { id: 2, step: 'Add clouds and arrows for cycle stages', completed: false },
        { id: 3, step: 'Label stages of the water cycle', completed: false },
      ],
      components: ['Poster board', 'Cotton balls (clouds)', 'Blue fabric (water)', 'Markers', 'Glue', 'Labels'],
    },
  },
  {
    id: 'science-4',
    type: 'science',
    title: 'Human Heart Model',
    description: 'Build a static model of the human heart to explore its anatomy and function.',
    image: getProjectImage('Human Heart Model'),
    category: 'Science',
    difficulty: 'Beginner',
    skills: ['Biology', 'Crafting', 'Anatomy'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Chambers', 'Valves', 'Major blood vessels'],
      tutorials: [
        { id: 1, step: 'Mold heart shape using clay', completed: false },
        { id: 2, step: 'Add chambers and vessels with paint', completed: false },
        { id: 3, step: 'Label parts of the heart', completed: false },
      ],
      components: ['Modeling clay', 'Acrylic paint', 'Small tubes (vessels)', 'Cardboard base', 'Glue', 'Labels'],
    },
  },
  {
    id: 'science-5',
    type: 'science',
    title: 'DNA Double Helix Model',
    description: 'Create a static model of the DNA double helix to understand its structure.',
    image: getProjectImage('DNA Double Helix Model'),
    category: 'Science',
    difficulty: 'Beginner',
    skills: ['Biology', 'Crafting', 'Molecular Science'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Double helix structure', 'Base pairs', 'Backbone'],
      tutorials: [
        { id: 1, step: 'Create backbone using straws or pipe cleaners', completed: false },
        { id: 2, step: 'Add base pairs with beads or foam', completed: false },
        { id: 3, step: 'Label DNA components', completed: false },
      ],
      components: ['Straws or pipe cleaners', 'Colored beads or foam', 'Cardboard base', 'Glue', 'Labels'],
    },
  },
  {
    id: 'science-6',
    type: 'science',
    title: 'Electric Circuit Model',
    description: 'Build a simple electric circuit to understand current flow.',
    image: getProjectImage('Electric Circuit Model'),
    category: 'Science',
    difficulty: 'Intermediate',
    skills: ['Physics', 'Crafting', 'Electronics'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Series circuit', 'Parallel circuit', 'Switch control'],
      tutorials: [
        { id: 1, step: 'Gather circuit components', completed: false },
        { id: 2, step: 'Assemble series circuit', completed: false },
        { id: 3, step: 'Add parallel circuit', completed: false },
      ],
      components: ['Battery', 'Wires', 'LEDs', 'Switch', 'Breadboard'],
    },
  },
  {
    id: 'science-7',
    type: 'science',
    title: 'Weather Station Model',
    description: 'Create a model to measure basic weather parameters.',
    image: getProjectImage('Weather Station Model'),
    category: 'Science',
    difficulty: 'Intermediate',
    skills: ['Meteorology', 'Crafting', 'Measurement'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Temperature', 'Humidity', 'Wind direction'],
      tutorials: [
        { id: 1, step: 'Build thermometer housing', completed: false },
        { id: 2, step: 'Add humidity sensor', completed: false },
        { id: 3, step: 'Create wind vane', completed: false },
      ],
      components: ['Thermometer', 'Hygrometer', 'Cardboard', 'Glue', 'Plastic sheets'],
    },
  },
  {
    id: 'science-8',
    type: 'science',
    title: 'Plant Cell Model',
    description: 'Construct a model of a plant cell to study its components.',
    image: getProjectImage('Plant Cell Model'),
    category: 'Science',
    difficulty: 'Beginner',
    skills: ['Biology', 'Crafting', 'Modeling'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Cell wall', 'Chloroplasts', 'Nucleus'],
      tutorials: [
        { id: 1, step: 'Create cell base with clay', completed: false },
        { id: 2, step: 'Add organelles with colored materials', completed: false },
        { id: 3, step: 'Label cell components', completed: false },
      ],
      components: ['Clay', 'Colored beads', 'Cardboard base', 'Glue', 'Labels'],
    },
  },
  {
    id: 'science-9',
    type: 'science',
    title: 'Bridge Structure Model',
    description: 'Build a model bridge to understand structural engineering.',
    image: getProjectImage('Bridge Structure Model'),
    category: 'Science',
    difficulty: 'Intermediate',
    skills: ['Physics', 'Crafting', 'Engineering'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Truss design', 'Load testing', 'Material strength'],
      tutorials: [
        { id: 1, step: 'Design bridge structure', completed: false },
        { id: 2, step: 'Assemble with craft materials', completed: false },
        { id: 3, step: 'Test load capacity', completed: false },
      ],
      components: ['Popsicle sticks', 'Glue', 'String', 'Cardboard base'],
    },
  },
  {
    id: 'science-10',
    type: 'science',
    title: 'Ecosystem Diorama',
    description: 'Create a diorama representing a specific ecosystem.',
    image: getProjectImage('Ecosystem Diorama'),
    category: 'Science',
    difficulty: 'Beginner',
    skills: ['Environmental Science', 'Crafting', 'Modeling'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Flora representation', 'Fauna representation', 'Terrain'],
      tutorials: [
        { id: 1, step: 'Create terrain base', completed: false },
        { id: 2, step: 'Add plant models', completed: false },
        { id: 3, step: 'Include animal figures', completed: false },
      ],
      components: ['Shoebox', 'Clay', 'Plastic figures', 'Paint', 'Glue'],
    },
  },
  // New Science Projects
  {
    id: 'science-11',
    type: 'science',
    title: 'Simple Pendulum',
    description: 'Demonstrate oscillation and period measurement.',
    image: getProjectImage('Simple Pendulum'),
    category: 'Science',
    difficulty: 'Beginner',
    skills: ['Physics', 'Measurement', 'Crafting'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Pendulum swing', 'Period calculation', 'Variable lengths'],
      tutorials: [
        { id: 1, step: 'Assemble pendulum', completed: false },
        { id: 2, step: 'Measure periods', completed: false },
        { id: 3, step: 'Analyze data', completed: false },
      ],
      components: ['String', 'Weight', 'Stand', 'Stopwatch'],
    },
  },
  {
    id: 'science-12',
    type: 'science',
    title: 'Magnetic Field Model',
    description: 'Visualize magnetic fields using iron filings.',
    image: getProjectImage('Magnetic Field Model'),
    category: 'Science',
    difficulty: 'Intermediate',
    skills: ['Physics', 'Electromagnetism', 'Modeling'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Field lines', 'Pole interactions', 'Electromagnet'],
      tutorials: [
        { id: 1, step: 'Set up magnets', completed: false },
        { id: 2, step: 'Add iron filings', completed: false },
        { id: 3, step: 'Observe patterns', completed: false },
      ],
      components: ['Magnets', 'Iron filings', 'Paper', 'Battery', 'Wire'],
    },
  },
  {
    id: 'science-13',
    type: 'science',
    title: 'Solar Panel Demo',
    description: 'Build a small solar-powered device.',
    image: getProjectImage('Solar Panel Demo'),
    category: 'Science',
    difficulty: 'Intermediate',
    skills: ['Physics', 'Renewable Energy', 'Electronics'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Energy conversion', 'Circuit integration', 'Efficiency test'],
      tutorials: [
        { id: 1, step: 'Assemble panel', completed: false },
        { id: 2, step: 'Connect to device', completed: false },
        { id: 3, step: 'Test under light', completed: false },
      ],
      components: ['Solar cell', 'LED', 'Wires', 'Resistor'],
    },
  },
  {
    id: 'science-14',
    type: 'science',
    title: 'Chemical Reaction Model',
    description: 'Demonstrate endothermic/exothermic reactions.',
    image: getProjectImage('Chemical Reaction Model'),
    category: 'Science',
    difficulty: 'Beginner',
    skills: ['Chemistry', 'Safety', 'Observation'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Temperature change', 'Color change', 'Gas production'],
      tutorials: [
        { id: 1, step: 'Prepare chemicals', completed: false },
        { id: 2, step: 'Mix and observe', completed: false },
        { id: 3, step: 'Record results', completed: false },
      ],
      components: ['Baking soda', 'Vinegar', 'Thermometer', 'Beakers'],
    },
  },
  {
    id: 'science-15',
    type: 'science',
    title: 'Ecosystem Terrarium',
    description: 'Create a self-sustaining mini ecosystem.',
    image: getProjectImage('Ecosystem Terrarium'),
    category: 'Science',
    difficulty: 'Advanced',
    skills: ['Biology', 'Environmental Science', 'Maintenance'],
    progress: 0,
    content: {
      type: 'science',
      features: ['Plant growth', 'Water cycle', 'Animal inclusion'],
      tutorials: [
        { id: 1, step: 'Set up container', completed: false },
        { id: 2, step: 'Add soil and plants', completed: false },
        { id: 3, step: 'Monitor ecosystem', completed: false },
      ],
      components: ['Glass jar', 'Soil', 'Plants', 'Small insects'],
    },
  },
];
